### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by maxest** [secarri/mip_flooding#1]
I've tried your tool but I think I am not getting expected results.

On input I have the following 24-bit img.png file:
![img](https://github.com/secarri/MipFlooding/assets/37375338/3f31e52f-1533-44e7-815b-d73ef039ca47)

And 8-bit mask.png file:
![mask](https://github.com/secarri/MipFlooding/assets/37375338/49f6c2cd-0734-47bb-b37f-6b61c9d25248)

On output I get this:
![out](https://github.com/secarri/MipFlooding/assets/37375338/c005d117-e329-4460-bea6-8f28a43dcd17)

Is that a correct output? It does not resemble the examples.

Here is the code I run:
```
from mipflooding import image_processing

file = "img.png"
mask = "mask.png"
output = "out.png"
image_processing.run_mip_flooding(file, mask, output)
```

Any idea what I could be doing wrong?

**Comment by secarri** [comment]
Hello @maxest :) It looks good to me. You're running the algorithm on a texture that's predominantly black except within the alpha zone. It's creating a background with the average color, which happens to be a deep shade of green, and then stacking each mip level on top of one another until reaching the original texture's resolution. Could you offer additional specifics or information on what you think is wrong?

**Comment by secarri** [comment]
Hello @maxest ,

I appreciate you bringing up this matter. I just wanted to follow up to ensure that everything is running smoothly. In order to keep the issue tracker as up to date as possible, I would like to close this issue. If you have more information to provide, please feel free to reopen it or create a new issue. 

Thank you :)

Best regards,

@secarri
